config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

#post 'issues/:id/token_vote/create', :to => 'recurring_tasks#create'
resources :issues do
    shallow do
      resources :token_votes, :controller => 'token_votes', :only => [:create, :destroy]
    end
end
get 'token_votes/walletnotify/:token_type_name/:txid', to: 'token_votes#walletnotify',
  as: 'walletnotify_token_votes'
get 'token_votes/blocknotify/:token_type_name/:blockhash', to: 'token_votes#blocknotify',
  as: 'blocknotify_token_votes'

resources :token_withdrawals, :only => [:create, :destroy]
post 'token_withdrawals/payout', to: 'token_withdrawals#payout',
  as: 'payout_token_withdrawals'

resources :token_types, :only => [:new, :create, :edit, :update, :destroy]

get 'my/token_votes', to: 'my#token_votes', as: 'my_token_votes'

app/views/settings/_checkpoints.html.erb
<table class="list" id="checkpoints">
  <thead>
    <tr>
      <th>Checkpoint order</th>
      <th>Checkpoint statuses</th>
      <th>Checkpoint vote share</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @settings['checkpoints']['statuses'].each_with_index do |statuses, index| %>
      <tr class="checkpoint-details">
        <td class="checkpoint-number"></td>
        <td>
          <%= select_tag "settings[checkpoints][statuses][]",
            options_for_checkpoint_statuses(@settings['checkpoints']['statuses'][index]),
            multiple: true %>
          <%= hidden_field_tag "settings[checkpoints][statuses][]" %>
        </td>
        <td>
          <%= number_field_tag "settings[checkpoints][shares][]",
            @settings['checkpoints']['shares'][index], in: 0.01..1, step: 0.01 %>
        </td>
        <td class="buttons">
          <%= link_to image_tag('delete.png'), '#', :class => 'delete-checkpoint-details' %>
        </td>
      </tr>
    <% end %>
    <td></td>
    <td><em class="info">Multiple choices allowed, minimum 1 required</em></td>
    <td><em class="info">Sum of shares has to equal 1.0</em></td>
    <td class="buttons">
      <%= link_to image_tag('add.png'), '#', :class => 'add-checkpoint-details' %>
    </td>
  </tbody>
</table>

<%= javascript_tag do %>
$('#checkpoints').on('click', 'a.delete-checkpoint-details', function(e) {
  e.preventDefault();
  if ($('#checkpoints tbody tr.checkpoint-details').length > 1) {
    $(this).parents('#checkpoints tr').remove();
  } else {
    $('#checkpoints tbody tr.checkpoint-details').find('input, select').val('');
  }
});
$('#checkpoints').on('click', 'a.add-checkpoint-details', function(e) {
  e.preventDefault();
  var row = $('#checkpoints tr.checkpoint-details:last');
  row.clone().insertAfter(row).find('input, select').val('');
});
<% end %>

app/views/settings/_token_types.html.erb
<% if @token_types.any? %>
  <div class="autoscroll">
    <table class="list">
      <thead>
        <tr>
          <th>Name</th>
          <th><span>RPC URI</span></th>
          <th>Confirms</th>
          <th>Default?</th>
          <th>Last block #</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @token_types.each do |token_type| %>
          <tr>
            <td class="name"><%= token_type.name %></td>
            <td><%= token_type.rpc_uri %></td>
            <td><%= token_type.min_conf %></td>
            <td><%= checked_image token_type.is_default %></td>
            <td><%= token_type.prev_sync_height %></td>
            <td class="buttons">
              <%= link_to(l(:button_delete), token_type_path(token_type), method: :delete,
                          class: 'icon icon-del') if token_type.deletable? %>
              <%= link_to(l(:button_edit), edit_token_type_path(token_type),
                          class: 'icon icon-edit') %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="nodata"><%= l(:label_no_data) %></div>
<% end %>

app/views/settings/_token_votes.html.erb
  <i>Token types define tokens e.g. BTC, BCH, LTC that can be used to vote.
  Checkpoints define issue statuses, which are awarded with share of tokens votes.
  At least 1 token type and 1 checkpoint is necessary to use this plugin.</i>
</div>

<div class="contextual">
  <%= link_to "New token type", new_token_type_path, :class => 'icon icon-add' %>
</div>

<h3>Token types</h3>
<div>
  <%= render partial: 'settings/token_types' %>
</div>

<h3>Checkpoints</h3>
<div>
  <p><%= render partial: 'settings/checkpoints' %></p>
</div>